-- Updated by データベース設計書_V0.93.xls

CREATE TABLE DAT_PROCESS
   (PROCESSID int NOT NULL,
    WORKITEMID  nvarchar(20) NOT NULL, 
    TEMPLATEID  nvarchar(20), 
    LASTUPDATETIME  nvarchar(17),
     PRIMARY KEY (PROCESSID,WORKITEMID)
   );
   
   
   CREATE TABLE DAT_WORKITEM
   (WORKITEMID  nvarchar(20)NOT NULL, 
    TASKID  nvarchar(20)NOT NULL, 
    TEMPLATEID  nvarchar(20), 
    LASTHISTORYNO int NOT NULL,
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (WORKITEMID)
   );
   
   CREATE TABLE DAT_FOLDERITEM 
   (WORKITEMID  nvarchar(20) NOT NULL, 
    FOLDERITEMNO  nvarchar(20) NOT NULL, 
    FOLDERITEMORDER int NOT NULL,
    TEMPLATEID  nvarchar(20),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO)
   );

   CREATE TABLE DAT_DOCUMENT
   (WORKITEMID  nvarchar(20) NOT NULL,
    FOLDERITEMNO  nvarchar(20) NOT NULL,
    DOCUMENTNO  nvarchar(20) NOT NULL,
    DOCUMENTORDER int NOT NULL,
    TEMPLATEID  nvarchar(20),
    PAGECOUNT int NOT NULL,
    VIEWINFORMATION  nvarchar(MAX),
    DOCUMENTTYPE  nvarchar(20),
    LASTUPDATETIME  nvarchar(17),
    --CONSTRAINT ENSURE_JSON1 CHECK (VIEWINFORMATION IS JSON) ENABLE,
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );

   CREATE TABLE DAT_LAYER
   (WORKITEMID  nvarchar(20) NOT NULL,
    FOLDERITEMNO  nvarchar(20) NOT NULL,
    DOCUMENTNO  nvarchar(20) NOT NULL,
    LAYERNO  nvarchar(20) NOT NULL,
    LAYERORDER int NOT NULL,
    LAYERNAME  nvarchar(255) NOT NULL,
    TEMPLATEID  nvarchar(20), 
    OWNERID  nvarchar(255) NOT NULL,
    ANNOTATIONS  nvarchar(MAX),
    INSERTDATETIME  nvarchar(17),
    LASTUPDATETIME  nvarchar(17),
    --CONSTRAINT ENSURE_JSON2 CHECK (ANNOTATIONS IS JSON) ENABLE,
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO,LAYERNO,OWNERID)
   );
   
    CREATE TABLE STR_DATA_FILE 
   (WORKITEMID  nvarchar(20) NOT NULL, 
    FOLDERITEMNO  nvarchar(20) NOT NULL, 
    DOCUMENTNO  nvarchar(20) NOT NULL,
    DOCUMENTDATAPATH  nvarchar(260), 
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );

    CREATE TABLE STR_LOG_ACCESS
   (EVENTID  nvarchar(20) NOT NULL, 
    PROCESSTIME  nvarchar(17), 
    USERID  nvarchar(255) NOT NULL,
    WORKITEMID  nvarchar(20) NOT NULL, 
    HISTORYNO int NOT NULL,
    TASKID  nvarchar(20) NOT NULL,
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE CTL_EVENT 
   (EVENTID  nvarchar(20) NOT NULL, 
    USERID  nvarchar(255) NOT NULL, 
    WORKITEMID  nvarchar(20) NOT NULL,
    STATUS  nvarchar(20), 
    TASKID  nvarchar(20) NOT NULL,
    TRANSACTIONTOKEN  nvarchar(255),
    WORKITEMDATA  nvarchar(MAX),
    LASTUPDATETIME  nvarchar(17),
    --CONSTRAINT ENSURE_JSON3 CHECK (WORKITEMDATA IS JSON) ENABLE,
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE MGR_TEMPLATE 
   (TEMPLATEID  nvarchar(20) NOT NULL, 
    TEMPLATENAME  nvarchar(255), 
    TEMPLATETABLENAME  nvarchar(255),
    TEMPLATEFIELD  nvarchar(MAX),
    TEMPLATETYPE  nvarchar(255),
    LASTUPDATETIME  nvarchar(17),
    --CONSTRAINT ENSURE_JSON5 CHECK (TEMPLATEFIELD IS JSON) ENABLE,
    PRIMARY KEY (TEMPLATEID)
   );
   
   CREATE TABLE CTL_TEMPLATE 
   (USERID  nvarchar(255) NOT NULL, 
    TEMPLATEID  nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY  nvarchar(20),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_TEMPLATE_P 
   (PROFILEID  nvarchar(255) NOT NULL, 
    TEMPLATEID  nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY  nvarchar(20),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (PROFILEID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_TEMPLATE_U 
   (USERID  nvarchar(255) NOT NULL, 
    TEMPLATEID  nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY  nvarchar(20),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_PROCESS 
   (PROCESSID int NOT NULL, 
    PROCESSNAME  nvarchar(255), 
    PROCESSVERSION float,
    DESCRIPTION  nvarchar(255),
    PROCESSDEFINITION  nvarchar(MAX),
    DOCUMENTDATASAVEPATH  nvarchar(260),
    LASTUPDATETIME  nvarchar(17),
    --CONSTRAINT ENSURE_JSON4 CHECK (PROCESSDEFINITION IS JSON) ENABLE,
    PRIMARY KEY (PROCESSID)
   );
   
   CREATE TABLE MGR_SCHEDULE 
   (SCHEDULEID int NOT NULL, 
    HOSTNAME  nvarchar(255),
    PROCESSISERVICEID int,
    TASKID  nvarchar(20) NOT NULL,
    STARTTIME  nvarchar(17),
    ENDTIME  nvarchar(17),
    ENABLE_DISABLE  nvarchar(20) NOT NULL,
    NEXTRUNDATE  nvarchar(17),
    RUNINTERVALDAY  nvarchar(8),
    RUNINTERVALHOUR  nvarchar(2),
    RUNINTERVALMINUTE  nvarchar(2),
    RUNINTERVALSECOND  nvarchar(2),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (SCHEDULEID)
   );
   
    CREATE TABLE MGR_STRAGE_FILE 
   (PROCESSID int NOT NULL,
    SITEID int,
    SITEMANAGEMENTTYPE  nvarchar(MAX),
    LASTUPDATETIME  nvarchar(17),
     PRIMARY KEY (PROCESSID)
   );
   
   CREATE TABLE MGR_STRAGE_DB 
   (PROCESSID int NOT NULL,
    SCHEMANAME  nvarchar(255), 
    DBUSER  nvarchar(255),
    DBPASSWORD  nvarchar(515),
    OWNER  nvarchar(255),
    DBSERVER  nvarchar(255),
    LASTUPDATETIME  nvarchar(17),
     PRIMARY KEY (PROCESSID)
   );
   
   CREATE TABLE MGR_TASK 
   (TASKID  nvarchar(20) NOT NULL, 
    TASKNAME  nvarchar(255), 
    CUSTOMTASKID  nvarchar(20),
    PROCESSID int NOT NULL,
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (TASKID)
   )