CREATE TABLE STR_DATA_DB
   (WORKITEMID  nvarchar(20) NOT NULL, 
    FOLDERITEMNO  nvarchar(20) NOT NULL, 
    DOCUMENTNO  nvarchar(20) NOT NULL,
    DOCUMENTDATA  nvarchar(MAX), 
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
)